try {
  process.loadEnvFile();
} catch {
  // No .env file present (e.g. production containers inject env vars directly) — safe to ignore.
}

import "./lib/otelInitializer.js";
import express from "express";
import path from "path";
import http from "http";
import { Server as SocketIOServer } from "socket.io";
import cookieParser from "cookie-parser";
import helmet from "helmet";
import cors from "cors";
import { randomUUID } from "crypto";
import { Redis } from "ioredis";
import { verifyToken } from "./src/lib/auth-tokens.js";
import { getRedisUrl } from "./src/lib/env.js";
import { runWithRequestId } from "./src/lib/requestContext.js";
import { csrfProtection } from "./src/middlewares/index.js";
import { hasPermission } from "./src/middlewares/rbac.js";
import { createHealthRouter } from "./src/routes/health.routes.js";
import apiRoutes from "./src/routes/index.js";
import telephonyRoutes from "./src/routes/telephony.routes.js";
import atlasgrRoutes from "./src/features/prospecting/routes/atlasgr.routes.js";
import { otelCollector } from "./lib/voice-runtime/otel.js";
import { logger } from "./src/lib/logger.js";
import { startWebhookWorker } from "./src/services/webhook.worker.js";
import { startRetentionScheduler } from "./src/services/retentionScheduler.js";
import fs from "fs";
import swaggerUi from "swagger-ui-express";
import yaml from "yaml";

async function startServer() {
  const app = express();
  const PORT = Number(process.env.PORT) || 3000;
  const server = http.createServer(app);
  const demoTelemetryEnabled =
    process.env.NODE_ENV !== 'production' && process.env.ENABLE_DEMO_TELEMETRY === 'true';

  const rawOrigins = (process.env.ALLOWED_ORIGINS || `http://localhost:${PORT}`)
    .split(',')
    .map((o) => o.trim())
    .filter(Boolean);

  const allowedOrigins = rawOrigins.map((origin) => {
    try {
      new URL(origin);
      return origin;
    } catch {
      logger.warn(`Invalid origin ignored in ALLOWED_ORIGINS: ${origin}`);
      return null;
    }
  }).filter(Boolean) as string[];

  const corsOriginOption = (origin: string | undefined, callback: (err: Error | null, allow?: boolean) => void) => {
    if (!origin || allowedOrigins.includes(origin)) {
      callback(null, true);
    } else {
      callback(null, false);
    }
  };

  const io = new SocketIOServer(server, {
    cors: { origin: corsOriginOption, methods: ["GET", "POST"], credentials: true },
  });

  // Synthetic observability data is strictly opt-in for local demonstrations. Production must
  // only show telemetry generated by real sessions so operational dashboards cannot be confused
  // with seeded/demo activity.
  if (demoTelemetryEnabled && otelCollector.getSpans().length === 0) {
    const ses1 = "sess-12345";
    const ses2 = "sess-67890";

    const s1 = otelCollector.startLocalSpan("EmotionEngine.analyzeTurn", ses1, { text: "Estou preocupada com o orçamento aprovado" });
    otelCollector.endLocalSpan(s1, { detectedEmotions: ["Ansiedade"], intensity: 85 });

    const s2 = otelCollector.startLocalSpan("IntentEngine.analyzeIntent", ses1, { context: "Qualificação inicial" });
    otelCollector.endLocalSpan(s2, { primaryIntent: "Agendar consulta", confidence: 95 });

    const s3 = otelCollector.startLocalSpan("StrategyEngine.adaptStrategy", ses1);
    otelCollector.endLocalSpan(s3, { tone: "Comforting", empathyLevel: "High" });

    const s4 = otelCollector.startLocalSpan("EmotionEngine.analyzeTurn", ses2, { text: "Tudo bem, deu certo o agendamento" });
    otelCollector.endLocalSpan(s4, { detectedEmotions: ["Satisfação"], intensity: 90 });

    otelCollector.recordLocalMetric('emotion_intensity', 85, { emotion: 'Ansiedade', sessionId: ses1 });
    otelCollector.recordLocalMetric('intent_confidence', 95, { primaryIntent: 'Agendar consulta', sessionId: ses1 });
    otelCollector.recordLocalMetric('emotion_intensity', 90, { emotion: 'Satisfação', sessionId: ses2 });
  }

  // Correlation ID: every request gets a UUID (or reuses an upstream-supplied one), echoed back
  // in the response and threaded through every log line emitted while handling the request.
  app.use((req, res, next) => {
    const requestId = (req.headers['x-request-id'] as string | undefined) || randomUUID();
    res.setHeader('X-Request-Id', requestId);
    runWithRequestId(requestId, next);
  });

  app.use(helmet({
    contentSecurityPolicy: {
      directives: {
        defaultSrc: ["'self'"],
        scriptSrc: ["'self'", "'unsafe-inline'"],
        // index.css pulls the Inter/JetBrains Mono webfonts from Google Fonts.
        styleSrc: ["'self'", "'unsafe-inline'", "https://fonts.googleapis.com"],
        fontSrc: ["'self'", "https://fonts.gstatic.com"],
        imgSrc: ["'self'", "data:", "blob:", "https:"],
        mediaSrc: ["'self'", "data:", "blob:"],
        connectSrc: ["'self'", "ws:", "wss:", "https:"],
        objectSrc: ["'none'"],
        frameAncestors: ["'none'"],
        upgradeInsecureRequests: [],
      },
    },
  }));
  app.use(cors({ origin: corsOriginOption, credentials: true }));
  app.use(cookieParser());

  // Redis-backed Rate Limiter
  const redisUrl = getRedisUrl();
  // Bounded retries + short timeouts so a Redis outage makes rate-limit/health checks fail fast
  // and degrade gracefully, instead of hanging every request forever waiting on the command queue.
  const redisClient = new Redis(redisUrl, { maxRetriesPerRequest: 1, connectTimeout: 2000, commandTimeout: 2000 });
  redisClient.on('error', (err) => logger.error('Redis client error', err.message));

  const createRateLimiter = (keyPrefix: string, limit: number, windowSeconds: number) =>
    async (req: express.Request, res: express.Response, next: express.NextFunction) => {
      const ip = req.ip || (req.headers['x-forwarded-for'] as string) || 'unknown';
      const key = `ratelimit:${keyPrefix}:${ip}`;

      try {
        const current = await redisClient.incr(key);
        if (current === 1) {
          await redisClient.expire(key, windowSeconds);
        }
        if (current > limit) {
          return res.status(429).json({ error: "Limite de requisições excedido. Tente novamente em um minuto." });
        }
        next();
      } catch {
        next();
      }
    };

  // General limiter for the whole API, applied before body parsing so an oversized/malformed
  // body never gets parsed for a request that's about to be rejected anyway.
  app.use(createRateLimiter('global', 200, 60));
  // Tighter limiter on login/register specifically — brute-force/credential-stuffing protection
  // that the shared 200 req/min global limit doesn't provide.
  app.use(['/api/auth/login', '/api/auth/register'], createRateLimiter('auth', 10, 60));

  // Twilio webhooks: mounted before csrfProtection/express.json() because Twilio sends
  // application/x-www-form-urlencoded bodies with no Origin header (the CSRF check would reject
  // every request). Authenticity is instead verified per-request via the Twilio request signature
  // inside telephonyRoutes — see validateTwilioSignature.
  app.use('/api', createRateLimiter('telephony', 120, 60), telephonyRoutes);

  // AtlasGR/Bland AI webhooks: same reasoning as telephonyRoutes above — these are
  // server-to-server calls (the AtlasGR CRM backend, the Bland AI call-result callback) that
  // never send an Origin header, so csrfProtection would reject every request in production.
  // Authenticity is verified per-route instead: a pre-shared secret header for the AtlasGR
  // webhook, a token embedded in the callback URL for the Bland AI callback — see
  // src/features/prospecting/routes/atlasgr.routes.ts.
  app.use('/api', atlasgrRoutes);

  app.use(csrfProtection);
  app.use(express.json());

  const healthRouter = createHealthRouter(redisClient);
  app.use(healthRouter);
  app.use('/api', healthRouter);
  app.use('/api', apiRoutes);

  // OpenAPI / Swagger Documentation
  try {
    const file = fs.readFileSync(path.join(process.cwd(), 'docs', 'api', 'openapi.yaml'), 'utf8');
    const swaggerDocument = yaml.parse(file);
    app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));
  } catch (err) {
    logger.error('Failed to load openapi.yaml for Swagger UI', err);
  }
  // Socket.io WebSocket Event Streaming Integration (authenticated)
  io.use((socket, next) => {
    const cookieHeader = socket.handshake.headers.cookie || '';
    const tokenFromCookie = cookieHeader
      .split(';')
      .map((c) => c.trim())
      .find((c) => c.startsWith('access_token='))
      ?.split('=')[1];
    const token = tokenFromCookie || (socket.handshake.auth?.token as string | undefined);

    const session = token ? verifyToken(decodeURIComponent(token)) : null;
    if (!session) {
      return next(new Error('unauthorized'));
    }
    socket.data.user = session;
    next();
  });

  // Room key for a watched call: scoped by tenant AND session, so a broadcast (intervention,
  // future real telemetry) can never reach a socket outside the tenant/session it belongs to,
  // even if two tenants happen to reuse the same sessionId. See handoff
  // 11-para-00-socketio-tenant-rbac-audit.md (Agente 11 -> Coordenador) — this closes it.
  const watchRoom = (tenantId: string, sessionId: string) => `watch:${tenantId}:${sessionId}`;

  io.on("connection", (socket) => {
    logger.info('Supervisor connected via WebSocket', socket.id);

    socket.on("watch_session", (data: { sessionId?: string }) => {
      const sessionId = data?.sessionId;
      if (typeof sessionId !== 'string' || !sessionId) return;
      socket.join(watchRoom(socket.data.user.tenantId, sessionId));
    });

    let demoInterval: NodeJS.Timeout | undefined;
    if (demoTelemetryEnabled) {
      let callDuration = 0;
      demoInterval = setInterval(() => {
        callDuration++;

        let emotions = { empathy: 85, confidence: 90, frustration: 10 };
        let intent = { primary: 'Fornecer informações', confidence: 90 };
        const objections: string[] = [];
        const alerts: Array<{ id: string; level: string; message: string; timestamp: number }> = [];

        if (callDuration < 12) {
          emotions = { empathy: 84, confidence: 89, frustration: 6 };
          intent = { primary: 'Identificação & Saudação (Live Stream)', confidence: 96 };
        } else if (callDuration < 30) {
          emotions = { empathy: 87, confidence: 93, frustration: 10 };
          intent = { primary: 'Coleta de CNPJ do Lead (Live Stream)', confidence: 99 };
          if (callDuration >= 15) {
            alerts.push({ id: 'a-1', level: 'info', message: 'CNPJ recebido e validado com sucesso no CRM via WebSocket.', timestamp: Date.now() });
          }
        } else if (callDuration < 55) {
          emotions = { empathy: 90, confidence: 95, frustration: 18 };
          intent = { primary: 'Qualificação de Necessidade / Objeções (Live Stream)', confidence: 92 };
          if (callDuration >= 35) {
            alerts.push({ id: 'a-2', level: 'warning', message: 'Lead relata objeção de preço em relação ao concorrente (WebSocket Stream).', timestamp: Date.now() });
            objections.push('Solicitou desconto para fechamento no mesmo dia');
          }
        } else {
          emotions = { empathy: 96, confidence: 98, frustration: 4 };
          intent = { primary: 'Agendamento e Finalização (Live Stream)', confidence: 98 };
          if (callDuration >= 58) {
            alerts.push({ id: 'a-3', level: 'critical', message: 'Reunião comercial confirmada para amanhã às 14:00 via Socket.io.', timestamp: Date.now() });
          }
        }

        socket.emit("telemetry_stream", {
          sessionId: "live-ws-session",
          callDuration,
          emotions,
          intent,
          objections,
          alerts
        });
      }, 1000);
    }

    socket.on("intervene_call", async (data: { sessionId?: string }) => {
      const allowed = await hasPermission(socket.data.user, 'supervision:intervene');
      if (!allowed) {
        logger.warn('Intervention rejected: permission denied', { role: socket.data.user?.role, userId: socket.data.user?.id });
        socket.emit("intervention_error", { message: "Sem permissão para intervir nesta chamada." });
        return;
      }
      const sessionId = data?.sessionId;
      if (typeof sessionId !== 'string' || !sessionId) {
        logger.warn('Intervention rejected: missing sessionId', { userId: socket.data.user?.id });
        socket.emit("intervention_error", { message: "sessionId ausente na solicitação de intervenção." });
        return;
      }
      const room = watchRoom(socket.data.user.tenantId, sessionId);
      logger.info('Intervention received from supervisor', { sessionId, userId: socket.data.user?.id, tenantId: socket.data.user?.tenantId });
      // Scoped to the tenant+session room, never io.emit — a global broadcast would leak this
      // event to every connected socket across every tenant regardless of which call it concerns.
      io.to(room).emit("intervention_triggered", {
        sessionId,
        by: socket.data.user?.email,
        at: Date.now(),
      });
    });

    socket.on("disconnect", () => {
      if (demoInterval) clearInterval(demoInterval);
      logger.info('Supervisor disconnected', socket.id);
    });
  });

  // Centralized error handler
  app.use((err: unknown, _req: express.Request, res: express.Response, _next: express.NextFunction) => {
    logger.error('Unhandled request error', err);
    if (res.headersSent) return;
    res.status(500).json({ error: 'Erro interno no servidor.' });
  });

  const serveStaticBuild =
    process.env.NODE_ENV === 'production' || process.env.SERVE_STATIC_BUILD === 'true';

  if (serveStaticBuild) {
    // Production and local E2E smoke tests serve the exact compiled artifact from dist/. E2E uses
    // NODE_ENV=e2e so local HTTP cookies are not marked Secure; production still uses
    // NODE_ENV=production and therefore preserves Secure cookies with no bypass configuration.
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('/*splat', (_req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  } else if (process.env.NODE_ENV !== 'test') {
    const { createServer: createViteServer } = await import('vite');
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  }

  if (process.env.NODE_ENV !== 'test') {
    startWebhookWorker();
    startRetentionScheduler();
    server.listen(PORT, "0.0.0.0", () => {
      logger.info(`Server running on http://localhost:${PORT}`);
    });
  }

  return app;
}

export const appPromise = startServer();
